import type { FullProductWorkPlanItem } from "./fullProductWorkPlan";

export const SOFTWARE_PRODUCT_WORK_PLAN: readonly FullProductWorkPlanItem[] = [
  {
    kind: "software_product_specification",
    title: "Create the software product specification",
    priority: 64,
    estimatedCostUnits: 12,
    deliverableKind: "software_product_specification",
    dependsOnKinds: ["product_requirements", "patent_design_handoff"],
    inputSnapshot: {
      department: "software_product_design",
      stageId: 5,
      instructions: "Turn the validated invention record into a testable software product specification: users, jobs-to-be-done, functional requirements, non-functional requirements, platform targets, integrations, permissions, accessibility, privacy/security constraints, success criteria, assumptions, and explicit non-goals. Preserve evidence uncertainty and do not invent legal/compliance clearance.",
    },
  },
  {
    kind: "software_ux_flow_design",
    title: "Design software user journeys and UX flows",
    priority: 63,
    estimatedCostUnits: 12,
    deliverableKind: "software_ux_flow_design",
    dependsOnKinds: ["software_product_specification"],
    inputSnapshot: {
      department: "software_product_design",
      stageId: 5,
      instructions: "Design the primary user journeys, screens/states, information architecture, onboarding, empty/error/loading states, accessibility considerations, permissions, and critical interaction flows. Ground decisions in the target user and validated problem rather than generic UI conventions.",
    },
  },
  {
    kind: "software_architecture",
    title: "Design the software architecture",
    priority: 62,
    estimatedCostUnits: 14,
    deliverableKind: "software_architecture",
    dependsOnKinds: ["software_product_specification"],
    inputSnapshot: {
      department: "software_engineering",
      stageId: 5,
      instructions: "Design an implementation-ready software architecture covering client/server boundaries, services, APIs, integrations, data flow, authentication/authorization, scalability assumptions, observability, deployment model, failure handling, and technology tradeoffs. Flag architecture decisions needing specialist security, privacy, financial, health, or regulated-domain review.",
    },
  },
  {
    kind: "software_data_model",
    title: "Design the software data model and API contracts",
    priority: 61,
    estimatedCostUnits: 12,
    deliverableKind: "software_data_model_api_contracts",
    dependsOnKinds: ["software_architecture"],
    inputSnapshot: {
      department: "software_engineering",
      stageId: 5,
      instructions: "Define the core entities, relationships, retention considerations, sensitive-data boundaries, API contracts, validation rules, ownership/tenancy assumptions, migration concerns, and audit requirements. Minimize sensitive data and clearly identify privacy/security assumptions requiring verification.",
    },
  },
  {
    kind: "software_security_privacy_review",
    title: "Prepare software security and privacy readiness review",
    priority: 60,
    estimatedCostUnits: 16,
    deliverableKind: "software_security_privacy_readiness",
    dependsOnKinds: ["software_architecture", "software_data_model", "regulatory_screening"],
    inputSnapshot: {
      department: "software_engineering",
      stageId: 5,
      instructions: "Threat-model the proposed software at a product-readiness level. Cover authentication, authorization, secrets, sensitive data, abuse cases, logging, third-party integrations, data retention/deletion, privacy notices/consent questions, dependency risk, backup/recovery, incident considerations, and security testing. This is preparation, not a certification or legal compliance conclusion.",
      professionalGate: "security_or_privacy_review_when_required",
    },
  },
  {
    kind: "software_prototype_plan",
    title: "Plan the smallest useful software prototype",
    priority: 59,
    estimatedCostUnits: 8,
    deliverableKind: "software_prototype_plan",
    dependsOnKinds: ["software_product_specification", "software_ux_flow_design", "software_architecture"],
    inputSnapshot: {
      department: "software_prototype_build",
      stageId: 6,
      instructions: "Define the smallest working software prototype that can test the highest-risk product assumptions. Separate throwaway validation code from production-intent work, specify acceptance criteria and instrumentation, and avoid building features that do not reduce uncertainty.",
    },
  },
  {
    kind: "software_implementation_plan",
    title: "Create the software implementation plan",
    priority: 58,
    estimatedCostUnits: 12,
    deliverableKind: "software_implementation_plan",
    dependsOnKinds: ["software_prototype_plan", "software_data_model", "software_security_privacy_review"],
    inputSnapshot: {
      department: "software_prototype_build",
      stageId: 6,
      instructions: "Create a sequenced implementation plan with milestones, repository/module boundaries, dependencies, environment needs, feature flags, data migrations, test strategy, telemetry, rollout/rollback considerations, and explicit human/provider dependencies. Do not imply code has been built unless implementation evidence exists.",
    },
  },
  {
    kind: "software_qa_test_plan",
    title: "Create software QA and acceptance test plan",
    priority: 57,
    estimatedCostUnits: 10,
    deliverableKind: "software_qa_acceptance_plan",
    dependsOnKinds: ["software_product_specification", "software_implementation_plan"],
    inputSnapshot: {
      department: "software_engineering_release",
      stageId: 7,
      instructions: "Create an evidence-driven test plan covering unit/integration/end-to-end behavior, permissions, error states, accessibility, performance assumptions, security/privacy cases, data migration/rollback, supported devices/platforms, and release acceptance criteria. Never report tests as passed without real execution evidence.",
    },
  },
  {
    kind: "software_beta_release_readiness",
    title: "Prepare software beta release readiness",
    priority: 56,
    estimatedCostUnits: 10,
    deliverableKind: "software_beta_release_readiness",
    dependsOnKinds: ["software_qa_test_plan"],
    inputSnapshot: {
      department: "software_engineering_release",
      stageId: 7,
      instructions: "Prepare beta readiness: release scope, known risks, telemetry, support/feedback loop, privacy/security checks, rollback, staged rollout, test-user criteria, issue triage, and evidence required before broader launch. Do not claim a beta exists or passed testing without real deployment/test evidence.",
    },
  },
  {
    kind: "software_distribution_release_plan",
    title: "Prepare software distribution and production release plan",
    priority: 55,
    estimatedCostUnits: 10,
    deliverableKind: "software_distribution_release_plan",
    dependsOnKinds: ["software_beta_release_readiness", "brand_identity_system", "pricing_strategy"],
    inputSnapshot: {
      department: "software_engineering_release",
      stageId: 7,
      instructions: "Prepare the production distribution path appropriate to the product: web deployment, app stores, desktop distribution, enterprise rollout, or APIs. Cover store/deployment requirements, release artifacts, privacy/support pages, signing/credentials, monitoring, rollback, versioning, and approval steps. Never publish, submit, purchase, or accept legal terms without required human authorization.",
    },
  },
];
